/* empty css                      */import{a as p,S as d,i as a}from"./assets/vendor-CesYmgD5.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const g="57443063-5f386e005ea466bbe0c4b67c4",h="https://pixabay.com/api/";async function y(i){const r={key:g,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0};return(await p.get(h,{params:r})).data}const c=document.querySelector(".gallery"),u=document.querySelector(".loader"),b=new d(".gallery a",{captionsData:"alt",captionDelay:250});function L(i){const r=i.map(({webformatURL:o,largeImageURL:n,tags:e,likes:t,views:s,comments:f,downloads:m})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${n}">
            <img class="gallery-image" src="${o}" alt="${e}" />
          </a>
          <div class="info">
            <p class="info-item"><b>Likes</b> <br/>${t}</p>
            <p class="info-item"><b>Views</b> <br/>${s}</p>
            <p class="info-item"><b>Comments</b> <br/>${f}</p>
            <p class="info-item"><b>Downloads</b> <br/>${m}</p>
          </div>
        </li>`).join("");c.innerHTML=r,b.refresh()}function F(){c.innerHTML=""}function w(){u.classList.remove("is-hidden")}function A(){u.classList.add("is-hidden")}const l=document.querySelector("form");l.addEventListener("submit",i=>{i.preventDefault();const r=i.currentTarget.elements["search-text"].value.trim();if(!r){a.warning({title:"Caution",message:"Please fill out the search field!",position:"topRight"});return}F(),w(),y(r).then(o=>{if(o.hits.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FAFAFB",titleColor:"#FAFAFB",iconColor:"#FAFAFB"});return}L(o.hits)}).catch(o=>{a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(o)}).finally(()=>{A(),l.reset()})});
//# sourceMappingURL=index.js.map
